"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-24 05:43:11.095695
"""
from alembic import op
import sqlalchemy as sa


revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=True),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('target_type', sa.String(length=40), nullable=True),
    sa.Column('target_id', sa.String(length=64), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('provider_cache',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('provider', sa.String(length=80), nullable=False),
    sa.Column('text_hash', sa.String(length=64), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'text_hash', name='uq_provider_cache')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('documents',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('owner_id', sa.String(length=32), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.String(length=10), nullable=False),
    sa.Column('doc_type', sa.String(length=40), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('storage_key', sa.String(length=64), nullable=True),
    sa.Column('keep_for_similarity', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('file_deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_owner_id'), 'documents', ['owner_id'], unique=False)
    op.create_index(op.f('ix_documents_sha256'), 'documents', ['sha256'], unique=False)
    op.create_table('document_fingerprints',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.String(length=32), nullable=False),
    sa.Column('owner_id', sa.String(length=32), nullable=False),
    sa.Column('hash', sa.BigInteger(), nullable=False),
    sa.Column('paragraph_index', sa.Integer(), nullable=False),
    sa.Column('page', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_fingerprints_document_id'), 'document_fingerprints', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_fingerprints_owner_id'), 'document_fingerprints', ['owner_id'], unique=False)
    op.create_index('ix_fingerprint_owner_hash', 'document_fingerprints', ['owner_id', 'hash'], unique=False)
    op.create_table('document_versions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('document_id', sa.String(length=32), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=False),
    sa.Column('pages_estimated', sa.Boolean(), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('char_count', sa.Integer(), nullable=False),
    sa.Column('paragraph_count', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('language_confidence', sa.Float(), nullable=False),
    sa.Column('language_distribution', sa.JSON(), nullable=False),
    sa.Column('is_scanned', sa.Boolean(), nullable=False),
    sa.Column('ocr_used', sa.Boolean(), nullable=False),
    sa.Column('structure', sa.JSON(), nullable=False),
    sa.Column('structure_source', sa.String(length=10), nullable=False),
    sa.Column('warnings', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_versions_document_id'), 'document_versions', ['document_id'], unique=False)
    op.create_table('analyses',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('document_id', sa.String(length=32), nullable=False),
    sa.Column('version_id', sa.String(length=32), nullable=True),
    sa.Column('owner_id', sa.String(length=32), nullable=False),
    sa.Column('depth', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('stage', sa.String(length=40), nullable=False),
    sa.Column('message', sa.String(length=300), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['version_id'], ['document_versions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analyses_created_at'), 'analyses', ['created_at'], unique=False)
    op.create_index(op.f('ix_analyses_document_id'), 'analyses', ['document_id'], unique=False)
    op.create_index(op.f('ix_analyses_owner_id'), 'analyses', ['owner_id'], unique=False)
    op.create_index(op.f('ix_analyses_status'), 'analyses', ['status'], unique=False)
    op.create_table('analysis_results',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('analysis_id', sa.String(length=32), nullable=False),
    sa.Column('ai_likelihood', sa.Float(), nullable=True),
    sa.Column('ai_confidence', sa.String(length=8), nullable=False),
    sa.Column('ai_basis', sa.String(length=40), nullable=False),
    sa.Column('passages_analyzed', sa.Integer(), nullable=False),
    sa.Column('passages_flagged', sa.Integer(), nullable=False),
    sa.Column('flagged_word_share', sa.Float(), nullable=False),
    sa.Column('similarity_overall', sa.Float(), nullable=True),
    sa.Column('similarity_internal', sa.Float(), nullable=True),
    sa.Column('similarity_corpus', sa.Float(), nullable=True),
    sa.Column('similarity_external', sa.Float(), nullable=True),
    sa.Column('similarity_scope', sa.String(length=40), nullable=False),
    sa.Column('providers', sa.JSON(), nullable=False),
    sa.Column('provider_comparison', sa.JSON(), nullable=False),
    sa.Column('score_distribution', sa.JSON(), nullable=False),
    sa.Column('passage_positions', sa.JSON(), nullable=False),
    sa.Column('style', sa.JSON(), nullable=False),
    sa.Column('academic', sa.JSON(), nullable=False),
    sa.Column('paraphrase', sa.JSON(), nullable=False),
    sa.Column('repeated_phrases', sa.JSON(), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('methodology_version', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('analysis_id')
    )
    op.create_table('passage_analyses',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('analysis_id', sa.String(length=32), nullable=False),
    sa.Column('section_order', sa.Integer(), nullable=True),
    sa.Column('chapter_order', sa.Integer(), nullable=True),
    sa.Column('page', sa.Integer(), nullable=True),
    sa.Column('paragraph_index', sa.Integer(), nullable=False),
    sa.Column('paragraph_end', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('ai_likelihood', sa.Float(), nullable=False),
    sa.Column('confidence', sa.String(length=8), nullable=False),
    sa.Column('characteristics', sa.JSON(), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('provider_scores', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_passage_analyses_analysis_id'), 'passage_analyses', ['analysis_id'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('analysis_id', sa.String(length=32), nullable=False),
    sa.Column('owner_id', sa.String(length=32), nullable=False),
    sa.Column('format', sa.String(length=8), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_analysis_id'), 'reports', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_reports_owner_id'), 'reports', ['owner_id'], unique=False)
    op.create_table('section_results',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('analysis_id', sa.String(length=32), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('parent_order', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('page_start', sa.Integer(), nullable=True),
    sa.Column('page_end', sa.Integer(), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('ai_likelihood', sa.Float(), nullable=True),
    sa.Column('ai_confidence', sa.String(length=8), nullable=True),
    sa.Column('similarity', sa.Float(), nullable=True),
    sa.Column('suspicious_count', sa.Integer(), nullable=False),
    sa.Column('excluded_from_ai', sa.Boolean(), nullable=False),
    sa.Column('style_metrics', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_section_results_analysis_id'), 'section_results', ['analysis_id'], unique=False)
    op.create_table('similarity_matches',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('analysis_id', sa.String(length=32), nullable=False),
    sa.Column('match_type', sa.String(length=24), nullable=False),
    sa.Column('provider', sa.String(length=60), nullable=False),
    sa.Column('section_order', sa.Integer(), nullable=True),
    sa.Column('page', sa.Integer(), nullable=True),
    sa.Column('paragraph_index', sa.Integer(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('matched_text', sa.Text(), nullable=False),
    sa.Column('matched_page', sa.Integer(), nullable=True),
    sa.Column('matched_paragraph_index', sa.Integer(), nullable=True),
    sa.Column('matched_document_id', sa.String(length=32), nullable=True),
    sa.Column('matched_document_name', sa.String(length=255), nullable=True),
    sa.Column('source_title', sa.String(length=500), nullable=True),
    sa.Column('source_url', sa.String(length=1000), nullable=True),
    sa.Column('similarity', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_similarity_matches_analysis_id'), 'similarity_matches', ['analysis_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_similarity_matches_analysis_id'), table_name='similarity_matches')
    op.drop_table('similarity_matches')
    op.drop_index(op.f('ix_section_results_analysis_id'), table_name='section_results')
    op.drop_table('section_results')
    op.drop_index(op.f('ix_reports_owner_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_analysis_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_passage_analyses_analysis_id'), table_name='passage_analyses')
    op.drop_table('passage_analyses')
    op.drop_table('analysis_results')
    op.drop_index(op.f('ix_analyses_status'), table_name='analyses')
    op.drop_index(op.f('ix_analyses_owner_id'), table_name='analyses')
    op.drop_index(op.f('ix_analyses_document_id'), table_name='analyses')
    op.drop_index(op.f('ix_analyses_created_at'), table_name='analyses')
    op.drop_table('analyses')
    op.drop_index(op.f('ix_document_versions_document_id'), table_name='document_versions')
    op.drop_table('document_versions')
    op.drop_index('ix_fingerprint_owner_hash', table_name='document_fingerprints')
    op.drop_index(op.f('ix_document_fingerprints_owner_id'), table_name='document_fingerprints')
    op.drop_index(op.f('ix_document_fingerprints_document_id'), table_name='document_fingerprints')
    op.drop_table('document_fingerprints')
    op.drop_index(op.f('ix_documents_sha256'), table_name='documents')
    op.drop_index(op.f('ix_documents_owner_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('provider_cache')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
